#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_20/bin:$PATHexport PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_20/bin:$PATH
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_20/

cd $OPENSHIFT_REPO_DIR/build/socialnetwork
nohup bin/socialnetwork \
  -DapplyEvolutions.default=true \
  -Duser.home=$OPENSHIFT_TMP_DIR/fakehome \
  -Dhttp.address=$OPENSHIFT_DIY_IP \
  -Dhttp.port=$OPENSHIFT_DIY_PORT \
# -Dconfig.file=$OPENSHIFT_REPO_DIR/conf/production.conf \
  -Dpidfile.path=$OPENSHIFT_REPO_DIR/misc/pid.pid \
  > /tmp/play-log 2> /tmp/play-log &

